export const inventoryPageData = {
  inventoryItemImage: "#item_4_img_link img",
  inventoryItemName: '[data-test="inventory-item-name"]',
  hamburgerMenuButton: ".bm-burger-button",
  hamburgerMenuIcon: ".bm-icon",
  hamburgerMenuContainer: ".bm-menu",
  hamburgerMenuXButton: ".bm-cross-button",
  pageLogo: ".app_logo",
  pageTitle: '[data-test="title"]',
  filterButton: '[data-test="product-sort-container"]',
  footer: '[data-test="footer"]',
  twitter: '[data-test="social-twitter"]',
  facebook: '[data-test="social-facebook"]',
  linkedIn: '[data-test="social-linkedin"]',
  footerCopyright: '[data-test="footer-copy"]',
  cartButton: '[data-test="shopping-cart-link"]',
  inventoryItemDescription: '[data-test="inventory-item-desc"]',
  inventoryItemPrice: '[data-test="inventory-item-price"]',
  addToCartButton: '[data-test="add-to-cart-sauce-labs-backpack"]',
  hamburgerMenuOption: '[data-test="about-sidebar-link"]',
  hamburgerMenuOption2: '[data-test="logout-sidebar-link"]',
}
