import { elements, flows } from '../support'

describe('Login to the page using the standard user, click on the Cart icon, and assert the elements visible on the cart page', () => {
  before(() => {
    cy.clearLocalStorage() //neccessary step, because it keeps the state of added cart.
    flows.loginStandardUser()
  })
  it('Locate the price, and click the add to cart button on a product', () => {
    cy.get(elements.inventoryPageData.inventoryItemPrice)
      .should('be.visible')
      .and('contain.text', '$29.99')
    cy.get(elements.inventoryPageData.addToCartButton)
      .should('be.visible')
      .and('contain.text', 'Add to cart')
      .click()
    cy.scrollTo('top')
    cy.get(elements.inventoryPageData.cartBadge)
      .should('be.visible')
      .and('contain.text', '1')
  })
  it('Locate and click the Cart button', () => {
    cy.get(elements.inventoryPageData.cartButton)
      .should('be.visible')
      .and('have.class', 'shopping_cart_link')
      .click()
  })
  it('Locate and click the Continue Shopping button, add another product to the cart', () => {
    cy.get(elements.cartPageData.continueShoppingButton)
      .should('be.visible')
      .and('contains.text', 'Continue Shopping')
      .click()
    cy.get(elements.inventoryPageData.addToCartButton2)
      .should('be.visible')
      .and('contain.text', 'Add to cart')
      .click()
  })
  it('Locate and click the Cart button after adding the second product', () => {
    cy.get(elements.inventoryPageData.cartButton)
      .should('be.visible')
      .and('have.class', 'shopping_cart_link')
      .click()
  })
  it('Locate and click the Checkout button', () => {
    cy.get(elements.cartPageData.checkoutButton)
      .should('be.visible')
      .and('contains.text', 'Checkout')
      .click()
  })
  it('Checkout Page Step One - Assert the elements, fill the fields and click Continue', () => {
    cy.get(elements.inventoryPageData.pageTitle)
      .should('be.visible')
      .and('contain.text', 'Checkout: Your Information')
    cy.get(elements.inventoryPageData.pageLogo)
      .should('be.visible')
      .and('contain.text', 'Swag Labs')
    cy.get(elements.checkoutPageStepOne.firstName)
      .should('be.visible')
      .and('have.attr', 'placeholder', 'First Name')
      .type('Tra')
    cy.get(elements.checkoutPageStepOne.lastName)
      .should('be.visible')
      .and('have.attr', 'placeholder', 'Last Name')
      .type('Nev')
    cy.get(elements.checkoutPageStepOne.zipCode)
      .should('be.visible')
      .and('have.attr', 'placeholder', 'Zip/Postal Code')
      .type('1000')
    cy.get(elements.checkoutPageStepOne.cancelButton)
      .should('be.visible')
      .and('contain.text', 'Cancel')
    cy.get(elements.checkoutPageStepOne.continueButton)
      .should('be.visible')
      .and('have.attr', 'value', 'Continue')
      .click()
  })
  it('Checkout Page Step Two - Assert the elements, fill the fields and click Finish', () => {
    cy.get(elements.inventoryPageData.pageTitle)
      .should('be.visible')
      .and('contain.text', 'Checkout: Overview')
    cy.get(elements.checkoutPageStepTwo.paymentInfo)
      .should('be.visible')
      .and('contain.text', 'Payment Information:')
    cy.get(elements.checkoutPageStepTwo.paymentInfoValue)
      .should('be.visible')
      .and('contain.text', 'SauceCard #31337')
    cy.get(elements.checkoutPageStepTwo.shippingInfo)
      .should('be.visible')
      .and('contain.text', 'Shipping Information:')
    cy.get(elements.checkoutPageStepTwo.shippingInfoValue)
      .should('be.visible')
      .and('contain.text', 'Free Pony Express Delivery!')
    cy.get(elements.checkoutPageStepTwo.priceTotal)
      .should('be.visible')
      .and('contain.text', 'Price Total')
    cy.get(elements.checkoutPageStepTwo.totalLabel)
      .should('be.visible')
      .and('contain.text', 'Total: $43.18')
    cy.get(elements.checkoutPageStepTwo.finishButton)
      .should('be.visible')
      .and('contain.text', 'Finish')
      .click()
  })
})
